### ISSUE TITLE
Phasing Suffocation

### ISSUE THREAD

**Issue by DoctorDragosaur** [kgorins/origins-plus-plus-wiki#2]
Theres a bug where some of the origins suffocate when phasing. I'm not sure if it applies to all of them, but at least three different origins with the phasing ability have started suffocating when in a wall.

**Comment by kgorins** [comment]
Hello! As written on the main page, this is just a wikipedia for [Origins ++ mod](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus) created by TheQuantumXenon. I am not them, so please direct your questions towards the original page :)
