### ISSUE TITLE
Thornling Reinforced Gold Armor

### ISSUE THREAD

**Issue by DoctorCraft05** [kgorins/origins-plus-plus-wiki#4]
I made the reinforced armor that the thronling allows you to make but I see no difference from normal golden armor.

**Comment by kgorins** [comment]
Hi! As written on the main page, this is just a wikipedia for [Origins ++ mod](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus) created by TheQuantumXenon. I am not them, so please direct your mod relayed questions towards the original page :)

**Comment by kgorins** [comment]
Closing
