### ISSUE TITLE
Height of certain origins issue

### ISSUE THREAD

**Issue by CatFoodBowl** [kgorins/origins-plus-plus-wiki#5]
when being any origin that changes my height, I only see at the height i should see if im crouching, otherwise my perspective is normal. third person i am small as should be but perspective is wrong.

**Comment by kgorins** [comment]
NO BUGS OR TICKETS PLEASE

This is a wikipedia for [Origins ++ mod](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus) created by TheQuantumXenon. I am not them, so please direct your questions towards the original page :)
