### ISSUE TITLE
lost draconian

### ISSUE THREAD

**Issue by SpookyLIght** [kgorins/origins-plus-plus-wiki#7]
hello can some1 help me fix the bug were if i become a lost draconian and use the teleportation ability some other players will also teleport to me

**Comment by kgorins** [comment]
NO BUGS OR TICKETS PLEASE

This is a wikipedia for [Origins ++ mod](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus) created by TheQuantumXenon. I am not them, so please direct your questions towards the original page :)
