### ISSUE TITLE
Origins didn't exist

### ISSUE THREAD

**Issue by Nullus9** [kgorins/origins-plus-plus-wiki#8]
Hello, when I try to use origins (the origin selection screen does not appear, when I look at it from within the game), it says **that there is no origin**. I would be happy if a solution is found to my problem as soon as possible, because I need to open a server in about 1 month.

**Comment by kgorins** [comment]
Hi!
I think by this point it’s written everywhere in this git repo, but I’m not the developer that you’re searching for. Please go to the original page that is **not** the Wikipedia.
